services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    volumes:
      - /home/shurtado/data/wp:/var/www/html:ro
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
    environment:
      - WP_REDIS_HOST=redis
      - WP_REDIS_PORT=6379 
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_HOST=mariadb

      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=dummy
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_SECOND_USER=${WP_SECOND_USER}
      - WP_SECOND_EMAIL=${WP_SECOND_EMAIL}
    secrets:
      - wp_admin_password
      - wp_second_password
      - db_password
 
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_SUPERVISOR=${MYSQL_SUPERVISOR}

    secrets:
      - db_password
      - db_root_password
      - mysql_supervisor_password

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: bonus-redis
    networks:
      - inception
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: bonus-ftp
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
    restart: unless-stopped


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_second_password:
    file: ../secrets/wp_second_password.txt
  mysql_supervisor_password:
    file: ../secrets/mysql_supervisor_password.txt

      
networks:
  inception:
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shurtado/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shurtado/data/db

  redis_data:
    driver: local

