services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    volumes:
      - /home/shurtado/data/wp:/var/www/html:ro
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    volumes:
      - /home/shurtado/data/wp:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=mariadb

      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_SECOND_USER=${WP_SECOND_USER}
      - WP_SECOND_PASSWORD=${WP_SECOND_PASSWORD}
      - WP_SECOND_EMAIL=${WP_SECOND_EMAIL}
    secrets:
      - wp_admin_password
 
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    volumes:
      - /home/shurtado/data/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_SUPERVISOR=${MYSQL_SUPERVISOR}
      - MYSQL_SUPERVISOR_PASSWORD=${MYSQL_SUPERVISOR_PASSWORD}

    secrets:
      - db_password
      - db_root_password

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
networks:
  inception:

